# Sensitivity analysis: predictors plausibly available at initial notification.
numeric:
  - acft_age
  - altimeter
  - apt_dist
  - apt_elev
  - apt_dir_sin
  - apt_dir_cos
  - cert_max_gr_wt
  - dec_latitude
  - dec_longitude
  - ev_month_sin
  - ev_month_cos
  - ev_time_sin
  - ev_time_cos
  - fc_seats
  - gust_kts
  - num_eng
  - rwy_len
  - rwy_width
  - total_seats
  - sky_ceil_ht
  - sky_nonceil_ht
  - vis_sm
  - wind_dir_sin
  - wind_dir_cos
  - wind_vel_kts
  - wx_dew_pt
  - wx_temp
categorical:
  - acft_category
  - air_medical
  - certs_held
  - elt_install
  - elt_type
  - ev_country
  - ev_dow
  - ev_nr_apt_loc
  - ev_state
  - far_part
  - fixed_retractable
  - flt_plan_filed
  - gust_ind
  - homebuilt
  - ifr_equipped_cert
  - light_cond
  - second_pilot
  - site_seeing
  - sky_cond_ceil
  - sky_cond_nonceil
  - type_fly
  - unmanned
  - wind_dir_ind
  - wind_vel_ind
  - wx_cond_basic
